# Generated by Django 5.2.7 on 2025-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('mercado', models.CharField(max_length=3)),
                ('instrumento', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('secuencia', models.BigIntegerField()),
                ('numero_dividendo', models.BigIntegerField()),
                ('tipo_sociedad', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1)),
                ('valor_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_8', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_9', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_10', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_11', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_12', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_13', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_14', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_15', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_16', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_17', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_18', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_19', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_20', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_21', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_22', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_23', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_24', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_25', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_26', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_27', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_28', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_29', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_30', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_31', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_32', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_33', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_34', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_35', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_36', models.DecimalField(decimal_places=8, max_digits=9)),
                ('factor_37', models.DecimalField(decimal_places=8, max_digits=9)),
            ],
        ),
    ]
