# Generated by Django 5.2.8 on 2025-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_alter_usuario_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
