# Generated by Django 5.2.8 on 2025-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0004_usuario_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
